### ISSUE TITLE
Publish non webpack bundled code

### ISSUE THREAD

**Issue by travisperson** [mzabriskie/moxios#1]
Current `moxios` is published to npm with a webpack bundled file. This means that you must always pass an `axios` instance to `moxios.install()` as webpack rewrites all imports and will never use the `axios` install from `node_modules` in a project. It would be nice to see just a babel transform of the code be published to npm.

**Comment by wezleytsai** [comment]
@travisperson i couldn't figure out why it wasn't mocking...now i see why

**Comment by mzabriskie** [comment]
Fixed by #3. Will release soon.
