### ISSUE TITLE
moxios.install() does not seem to install adapter

### ISSUE THREAD

**Issue by jomag** [mzabriskie/moxios#15]
Hi,

I'm trying to use moxios, but I find that the requests are performed as usual and moxios.requests.mostRecent() returns undefined.

It seems that moxios does not install any mock adapter.

Here's a minimal test:

```javascript
import moxios from "moxios";
import axios from "axios";

describe("moxios", () => {
  it("mocks axios", () => {
    console.log("Adapter before: ");
    console.log(axios.defaults.adapter);
    moxios.install();
    console.log("Adapter after installing: ");
    console.log(axios.defaults.adapter);
    moxios.uninstall();
    console.log("Adapter after uninstalling: ");
    console.log(axios.defaults.adapter);
  });
});
```
Output:

```
Adapter before: 
[Function: httpAdapter]
Adapter after installing: 
[Function: httpAdapter]
Adapter after uninstalling: 
[Function: httpAdapter]
```
I run the test with this command:

```
node_modules/.bin/mocha --compilers js:babel-core/register moxios.js
```

**Comment by jomag** [comment]
I think I've found my error: if I change the install/uninstall calls to pass "axios" everything works. Not sure why though...

```javascript
import moxios from "moxios";
import axios from "axios";

describe("moxios", () => {
  it("mocks axios", () => {
    console.log("Adapter before: ");
    console.log(axios.defaults.adapter);
    moxios.install(axios);
    console.log("Adapter after installing: ");
    console.log(axios.defaults.adapter);
    moxios.uninstall(axios);
    console.log("Adapter after uninstalling: ");
    console.log(axios.defaults.adapter);
  });
});
```

**Comment by lucantini** [comment]
I had the exact same problem. I just updated my axios version to the 0.15.3 and it worked just fine, even without passing axios to the call of moxios.install

**Comment by mzabriskie** [comment]
If moxios is using the same version of axios as your app, you shouldn't need to pass axios to `moxios.install`. If you are using different versions, or you are using a custom instance, then passing an instance is required.

**Comment by leon-yum** [comment]
Hi this is still a problem for me, and doing `moxios.install(axios)` did not fix things :( https://stackoverflow.com/questions/49414373/moxios-typeerror-cannot-read-property-adapter-of-undefined

`"axios": "^0.16.2",`
