### ISSUE TITLE
moxios.requests.mostRecent() returns undefined

### ISSUE THREAD

**Issue by main-kun** [mzabriskie/moxios#2]
I use karma, jasmine and phantomJS with babel-polyfill. mostRecent always returns undefined even if I call axios in the test directly.

For example:
```coffeescript
axios = require 'axios'
moxios = require 'moxios'

describe 'Test moxios', () ->
  beforeEach () ->
    moxios.install()

  afterEach () ->
    moxios.uninstall()

  it 'mostRecent should return a request', () ->
    axios('http://example.com').then (result) -> console.log result
    moxios.wait () ->
      console.log moxios.requests.mostRecent()
      # undefined
```

**Comment by joshualcoffee** [comment]
This seems to be an issue when webpack builds the source.  If you run the test importing moxios from './dist/moxios' 7 test will fail.  

For now I just copied the index.js file and import it in to my test helper.  I may can give a helping hand to looking in to what could cause this.

**Comment by main-kun** [comment]
Hey @joshualcoffee, thank you for your help. Indeed, if i put moxios outside of node_modules and require the index file, it starts working. Though I had to add babel to my coffeescript project, would be great if i didn't have to do it.

**Comment by main-kun** [comment]
Also I just realised this was mentioned in #1. So it works if i pass axios to 'moxios.install()`

**Comment by ghasemikasra39** [comment]
I am facing the same issue, any solution?

**Comment by subrato31** [comment]
Same issue
