### ISSUE TITLE
How to mock reject reponse with status > 400

### ISSUE THREAD

**Issue by Sutikshan** [mzabriskie/moxios#6]
How to mock reject reponse with status > 400 .
I want to mock errorneous response i.g.

```
      moxios.wait(() => {
        const request = moxios.requests.mostRecent();
        request.respondWith({
          status: 422,
          response: { message: 'problem' },
        });
      });
```
How can I do it?

**Comment by Sutikshan** [comment]
I manage to do it via following :-
```
      const errResp = {
        status: 422,
        response: { message: 'problem' },
      };
      moxios.wait(() => {
        const request = moxios.requests.mostRecent();
        request.reject(errResp);
      });
```
Thanks for this lib.

**Comment by rickhanlonii** [comment]
For anyone using `stubRequest` you should be able to just use a non 2XX status:

```
moxios.stubRequest(/.*/, {
    status: 400,
    response: { message: 'problem' }
  });
```

@Sutikshan it looks like `respondWith` does this as well. [Here](https://github.com/mzabriskie/moxios/blob/8efab10affaa1d6f46ade94b58e48a2a35993fee/index.js#L140-L149) it calls `axois.settle` which as you can see [here](https://github.com/mzabriskie/axios/blob/b8f6f5049cf3da8126a184b6b270316402b5b374/lib/core/settle.js#L15) rejects for invalid response statuses. Not sure why it wasn't working for you.

**Comment by mrchief** [comment]
@rickhanlonii `request.reject` produces a cleaner JSON response whereas `respondWith` creates a Error instance itself (or something to that effect). Its very hard to do matchers on that one.

with `respondWith`
```
Expected value to match object:
      [{"status": "started", "type": "CONFIGURED_ACCOUNTS"}, {"error": {"status": 500}, "status": "failed", "type": "CONFIGURED_ACCOUNTS"}]
    Received:
      [{"status": "started", "type": "CONFIGURED_ACCOUNTS"}, {"error": [Error: Request failed with status code 500], "status": "failed", "type": "CONFIGURED_ACCOUNTS
ACCOUNTS"}]
```

with `reject`

```
error { status: 500,
        response:
         { title: 'mock error',
           description: 'mock error details',
           data: undefined } }
```

**Comment by yonasstephen** [comment]
@mrchief you can use `stubRequest` or `respondWith` and still easily match the error instance as follow by comparing the result with below instance:
```
const error = new Error('Error: Request failed with status code 500')

moxios.stubRequest('/api', {
   status: 501,
   response: { error }

```

**Comment by mrchief** [comment]
Its not an issue with moxios, just a quirk of axios: https://github.com/axios/axios/issues/960#issuecomment-320659373

Went with the interceptor approach and now I can reliably check my asserts.
